/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package analexflexx;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author acer
 */
public class LEXFRMArchi extends javax.swing.JFrame {

    JFileChooser seleccionar= new JFileChooser();
    File Archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    public LEXFRMArchi() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public String AbrirArchivo(File archivo){
        String documento="";
        try{
            entrada=new FileInputStream(archivo);
            int ascci;
            while((ascci=entrada.read())!=-1){
                char caracter=(char)ascci;
                documento+=caracter;
            }
        }catch(Exception e){
        }   
        return documento;
    }
    
    public String GuardarArchivo(File archivo,String documento){
        String mensaje=null;
        try{
            salida=new FileOutputStream(archivo);
            byte[] bytxt=documento.getBytes();
            salida.write(bytxt);
            mensaje="Archivo guardado";
        }catch(Exception e){
        }
        return mensaje;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAnalizarAr = new javax.swing.JButton();
        btnImportarAr = new javax.swing.JButton();
        btnGuardarEdit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnVolverA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        btnAnalizarAr.setBackground(new java.awt.Color(153, 255, 51));
        btnAnalizarAr.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnAnalizarAr.setText("ANALIZAR");
        btnAnalizarAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarArActionPerformed(evt);
            }
        });

        btnImportarAr.setBackground(new java.awt.Color(102, 153, 255));
        btnImportarAr.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnImportarAr.setText("IMPORTAR");
        btnImportarAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarArActionPerformed(evt);
            }
        });

        btnGuardarEdit.setBackground(new java.awt.Color(255, 204, 204));
        btnGuardarEdit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnGuardarEdit.setText("GUARDAR");
        btnGuardarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnImportarAr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnAnalizarAr, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnGuardarEdit)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEdit)
                    .addComponent(btnAnalizarAr)
                    .addComponent(btnImportarAr))
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 70));

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnVolverA.setBackground(new java.awt.Color(255, 255, 153));
        btnVolverA.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnVolverA.setText("VOLVER");
        btnVolverA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btnVolverA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAActionPerformed
        Inicio vistaLEXMAN = new Inicio();
        vistaLEXMAN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverAActionPerformed

    private void btnImportarArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarArActionPerformed
        if(seleccionar.showDialog(null, "Abrir")==JFileChooser.APPROVE_OPTION){
            Archivo=seleccionar.getSelectedFile();
            if(Archivo.canRead()){
                if(Archivo.getName().endsWith("txt")){
                    String documento=AbrirArchivo(Archivo);
                    txtArea.setText(documento);
                }else{
                    JOptionPane.showMessageDialog(null,"Formato incorrecto");
                    
                }
            }
        }
    }//GEN-LAST:event_btnImportarArActionPerformed

    private void btnGuardarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEditActionPerformed
        if(seleccionar.showDialog(txtArea, "Guardar")==JFileChooser.APPROVE_OPTION){
            Archivo=seleccionar.getSelectedFile();
             if(Archivo.getName().endsWith("txt")){
                String Documento=txtArea.getText();
                String mensaje= GuardarArchivo(Archivo,Documento);
                if(mensaje!=null){
                    JOptionPane.showMessageDialog(null, mensaje);
                }else{
                    JOptionPane.showMessageDialog(null, "Formato incorrecto");
                } 
            }else{
                 JOptionPane.showMessageDialog(null, "Guardado");
             }
        }
    }//GEN-LAST:event_btnGuardarEditActionPerformed

    private void btnAnalizarArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarArActionPerformed
        File archivo = new File("Alumno.txt");
        PrintWriter escribir;
        try {
            escribir = new PrintWriter(archivo);
            escribir.print(txtArea.getText());
            escribir.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LEXFRM.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Reader lector = new BufferedReader(new FileReader("Alumno.txt"));
            Lexer lexer = new Lexer(lector);
            String resultado = "TOKEN"+"\t\t"+"DESCRIPCION"+"\t\t"+"LEXEMA"+"\n";
            while(true){
                Tokens tokens = lexer.yylex();
                if(tokens == null){
                    resultado+="\n#";
                    txtArea.setText(resultado);
                    return;
                }
                switch(tokens){
                    case ERROR:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "EL SÍMBOLO NO EXISTE"+ "\n";
                        break;
                    case Identificador: 
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "100"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case LiteralNumeroEntero: 
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "300"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case Reservadas:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "400"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case Matricula1:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "5001"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case Matricula2:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "5002"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case Matricula3:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "5003"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case Credito:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "900"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case OperadorIgual:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "200"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case OperadorSuma:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "201"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case OperadorResta:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "202"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case OperadorMultiplicacion:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "203"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case OperadorDivision:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "204"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    case DNI:
                        resultado+= "--------------------------------------------------------------------------------------------------------------"+"\n"+
                                "800"+"\t\t"+tokens+"\t\t"+lexer.lexeme+ "\n";
                        break;
                    
                    default:
                        resultado+= "Token: "+ tokens + "\n";
                        break;
                
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LEXFRM.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LEXFRM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnalizarArActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEXFRMArchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEXFRMArchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEXFRMArchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEXFRMArchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEXFRMArchi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizarAr;
    private javax.swing.JButton btnGuardarEdit;
    private javax.swing.JButton btnImportarAr;
    private javax.swing.JButton btnVolverA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
